---
title: "Piazza (online communication)"
---

This term we will be using Piazza for class discussion. The system is highly catered to getting you help fast and efficiently from classmates, the TA, and myself. Rather than emailing questions to the teaching staff, I encourage you to post your questions on Piazza.

READ THE INFORMATION BELOW, IT'S **VERY** IMPORTANT.

# Piazza Rules

-   Do **not** share code solutions. You are free to share error messages, but not code. TAs and instructors can access your submission on gradescope.

-   It is expected that everyone will participate in the online discussion in a mature and respectful manner. Do not demean or embarrass others. Do not make sexist, racist, xenophobic, homophobic, transphobic, or victim-blaming comments. Immature, aggressive, or disrespectful behavior will not be tolerated. If you see anyone breaking this rule, report that person to me (adrianaps\@arizona.edu)

-   Be cautious of how you use humor in sessions and online. Be aware of the potential impact of your words, regardless of the intentions. Think through and reread your comments before you say/post them.
