---
title: "TAs and Office Hours"
---

The Undergraduate Teaching Assistants (UGTAs or TAs) in this class are here to help. You are also welcome to send an email.

The best way to talk with a particular TA is via office hours, so check the schedule (scroll down this page).

# Course Coordinators

Course coordinators are experienced UGTAs that assist the instructor with course management and will have a supervisory role with the course UGTAs.

-   Anthony Hsu 
-   Amyra White
-   Miro Vanek
-   Pearl McNabb

# Senior TA

-   Taoseef Aziz


# TAs

Undergraduate Teaching Assistants (UGTAs) in the Department of Computer Science assist instructors in delivering undergraduate computer science courses. CS introductory courses utilize active learning and collaborative learning spaces to provide a collaborative and supportive environment for students learning programming skills. All teaching assistants have taken and excelled in the courses they support and are familiar with the material to mentor new students as they learn.

## 1pm Section

-   Elias Zheng
-   Gabriel Hernandez
-   Garegin Mazmanyan
-   Madeline DeLeon
-   Taoseef Aziz
-   Steven Truong
-   Waldo Guzman Barrientos


## 2pm Section

-   Ali Sartaz Khan
-   Chitrangada Juneja
-   Nees Abusaada
-   Owen Chambers
-   Pri Vaghela
-   Samarie Tavenner
-   Zachary Nicolosi


Interested in becoming a TA in the future? Check out [more information about what TAs do and how to apply](https://www.cs.arizona.edu/ugta).

# Office Hours

Shown below is the office hours schedule. The in-person office hours are hosted in Gould-Simpson 856. Adriana's office hours are in GS 811. An (O) next to a name indicates that the office hour is online. For these office hours, log in to the class [discord](https://discord.gg/5JSa7fFSWR) server, put your name in the #office-hours text channel, and join the #office-hour voice channel.

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRwv6Ssty22U8FOKo28fqTnvez5sw0vlPrkcJiIe_3VXmdwY3bVqhO7TcQJip1yEmJLhljG1lgeCiy_/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false" width="100%" height="600px"></iframe>
